### ISSUE TITLE
Closing a dockable window causes it to crash when it's subsequently reopened

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#169]
Repro:

 - Bring up the Code Inspections window (or Code Explorer)
 - X-Close the Code Inspections window
 - [try to] bring up the same window again: boom, `System.Runtime.InteropServices.COMException`.

Message:

> *Error HRESULT E_FAIL has been returned from a call to a COM component.*

Stack trace:

>    *at Microsoft.Vbe.Interop._Windows.CreateToolWindow(AddIn AddInInst, String ProgId, String Caption, String GuidPosition, Object& DocObj)
   at Rubberduck.UI.DockablePresenterBase.CreateToolWindow(IDockableUserControl control) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\DockablePresenterBase.cs:line 29
   at Rubberduck.UI.DockablePresenterBase..ctor(VBE vbe, AddIn addin, IDockableUserControl control) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\DockablePresenterBase.cs:line 20
   at Rubberduck.UI.CodeInspections.CodeInspectionsDockablePresenter..ctor(IRubberduckParser parser, IEnumerable`1 inspections, VBE vbe, AddIn addin, CodeInspectionsWindow window) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeInspections\CodeInspectionsDockablePresenter.cs:line 24
   at Rubberduck.UI.CodeInspections.CodeInspectionsMenu.OnCodeInspectionsButtonClick(CommandBarButton ctrl, Boolean& canceldefault) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeInspections\CodeInspectionsMenu.cs:line 43*

---

Probably has something to do with the way the COM control is handled in the `DockablePresenterBase` class when the window closes. Skipping through the code in the debugger after this exception is thrown, results in being able to display the window again.

Added this code in the mean time:

        public virtual void Show()
        {
            try
            {
                _window.Visible = true;
            }
            catch (COMException e)
            {
                // bug: this exception shouldn't be happening. issue #169.
            }
        }

**Comment by retailcoder** [comment]
Closing this issue for now, as the app no longer crashes. This has been <s>fixed</s> patched by surrounding the `_window.Visible = true;` assignment by a `try/catch` block as shown above.

**Comment by ckuhn203** [comment]
Still an issue. The try/catch doesn't correct the behavior. 
I was able to fix the null reference exception by creating a new toolwindow if it's null.
I still don't know why it goes null to begin with, but it does have something to do with closing the window via the x button.

Interestingly enough, the Test Explorer does not suffer from this issue. If we can figure out why it works, maybe we can figure out why there's an issue with TodoExplorer and CodeExplorer.

**Comment by ckuhn203** [comment]
[the test explorer is... not using a base presenter :(](http://chat.stackexchange.com/transcript/message/20186869#20186869)
