### ISSUE TITLE
Having two identically named Projects open blows up Navigation

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#280]
# Stack Trace:

	System.InvalidOperationException: Sequence contains no matching element
	   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
	   at Rubberduck.UI.UnitTesting.TestExplorerDockablePresenter.OnExplorerGoToSelectedTest(Object sender, SelectedTestEventArgs e) in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerDockablePresenter.cs:line 121
	   at Rubberduck.UI.UnitTesting.TestExplorerWindow.GridCellDoubleClicked(Object sender, DataGridViewCellEventArgs e) in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\UnitTesting\TestExplorerWindow.cs:line 228
	   at System.Windows.Forms.DataGridViewCellEventHandler.Invoke(Object sender, DataGridViewCellEventArgs e)
	   at System.Windows.Forms.DataGridView.OnCellDoubleClick(DataGridViewCellEventArgs e)
	   at System.Windows.Forms.DataGridView.OnDoubleClick(EventArgs e)
	   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
	   at System.Windows.Forms.Control.WndProc(Message& m)
	   at System.Windows.Forms.DataGridView.WndProc(Message& m)
	   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
	   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
	   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

# [Relevant code:](https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/UI/UnitTesting/TestExplorerDockablePresenter.cs#L121-L125)

            var codeModule = this.VBE.VBProjects.Cast<VBProject>()
                     .First(project => project.Name == controlSelection.ProjectName)
                     .VBComponents.Cast<VBComponent>()
                     .First(component => component.Name == controlSelection.ModuleName)
                     .CodeModule;

# Repro:

1. Create a new workbook.
2. Create a second new workbook
3. Add a test module and test method
4. Double click record in gridview
5. *Boom*

# Note:

The Todo Explorer is exhibiting similar behavior, but seems to be swallowing the exception some how. May or may not be related.

**Comment by retailcoder** [comment]
Makes sense that two identically named projects would cause issues.. but this:

> *Sequence contains no matching element*

Means there was *no* element in the collection, not *too many*. This exception needs further investigation.

**Comment by ckuhn203** [comment]
I agree that it doesn't make sense, but changing one of the offending project names "corrected" the issue.

**Comment by ckuhn203** [comment]
It makes sense now. Consider this code. 

            var codeModule = this.VBE.VBProjects.Cast<VBProject>()
                     .First(project => project.Name == controlSelection.ProjectName)
                     .VBComponents.Cast<VBComponent>()
                     .First(component => component.Name == controlSelection.ModuleName)
                     .CodeModule;

If there are two identically named projects, but only **one of them** has the module name that is being searched for, the invalid operation exception is thrown. The component really doesn't exist (in that project).
