### ISSUE TITLE
Log Parsing Errors

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#411]
It would greatly help if we had a log of parse errors when investigating Code Inspection false positives. We can create a custom error listener that logs lexer and parser errors to a file for review.

As we're inspecting source code, that could be proprietary, I think we should conditionally compile this out of any release versions and only use it internally. There's an [example of a custom listener here][1]. It actually ensures exceptions are thrown, instead of swallowed, but should be a nice example of how we could log in the places where it throws exceptions.

[1]:https://github.com/ckuhn203/Antlr4Calculator/blob/master/Calculator/ThrowExceptionErrorListener.cs

**Comment by retailcoder** [comment]
I haven't implemented the log, but commit 87032ea66d51b1cb632aca6cf1f38e48323b8a14 (in the `GrammarIsFun` branch) introduces an error listener for the parser, so we can debug our buggy grammar.

I really feel like using NLog to implement the logging. Objections?

**Comment by ckuhn203** [comment]
None. :+1:  
I do think it's best to compile this out of release builds though. Like I said before, potentially proprietary code and all. It's not nice to log it like that.

**Comment by retailcoder** [comment]
I'd only log the stack trace and exception message. Example:

Message (only contains the faulty token out of the input stream - here a 'dot' token):

> A RecognitionException was thrown. line 66, position 9. Message: extraneous input '.' expecting {ACCESS, ADDRESSOF, ALIAS, AND, ATTRIBUTE, APPACTIVATE, APPEND, AS, BEGIN, BEEP, BINARY, BOOLEAN, BYVAL, BYREF, BYTE, CALL, CASE, CHDIR, CHDRIVE, CLASS, CLOSE, COLLECTION, CONST, DATABASE, DATE, DECLARE, DEFBOOL, DEFBYTE, DEFDATE, DEFDBL, DEFDEC, DEFCUR, DEFINT, DEFLNG, DEFOBJ, DEFSNG, DEFSTR, DEFVAR, DELETESETTING, DIM, DO, DOUBLE, EACH, ELSE, ELSEIF, END, ENUM, EQV, ERASE, ERROR, EVENT, FALSE, FILECOPY, FRIEND, FOR, FUNCTION, GET, GLOBAL, GOSUB, GOTO, IF, IMP, IMPLEMENTS, IN, INPUT, IS, INTEGER, KILL, LOAD, LOCK, LONG, LOOP, LEN, LET, LIB, LIKE, LSET, ME, MID, MKDIR, MOD, NAME, NEXT, NEW, NOT, NOTHING, NULL, ON, OPEN, OPTIONAL, OR, OUTPUT, PARAMARRAY, PRESERVE, PRINT, PRIVATE, PUBLIC, PUT, RANDOM, RANDOMIZE, RAISEEVENT, READ, REDIM, REM, RESET, RESUME, RETURN, RMDIR, RSET, SAVEPICTURE, SAVESETTING, SEEK, SELECT, SENDKEYS, SET, SETATTR, SHARED, SINGLE, SPC, STATIC, STEP, STOP, STRING, SUB, TAB, TEXT, THEN, TIME, TO, TRUE, TYPE, TYPEOF, UNLOAD, UNLOCK, UNTIL, VARIANT, VERSION, WEND, WHILE, WIDTH, WITH, WITHEVENTS, WRITE, XOR, IDENTIFIER, NEWLINE, WS}

Stack trace:

>  at Rubberduck.Parsing.Listeners.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Listeners\ExceptionErrorListener.cs:line 12
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.SingleTokenDeletion(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.certainIdentifier() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 14402
   at Rubberduck.Parsing.Grammar.VBAParser.iCS_B_ProcedureCall() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 12328
   at Rubberduck.Parsing.Grammar.VBAParser.implicitCallStmt_InBlock() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 12270
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1975
   at Rubberduck.Parsing.Grammar.VBAParser.block() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1542
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 9238
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1286
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1171
   at Rubberduck.Parsing.Grammar.VBAParser.module() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 408
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in c:\Users\Mathieu\Source\Repos\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 217
   at Rubberduck.VBA.RubberduckParser.Parse(String code, TokenStreamRewriter& outRewriter) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\VBA\RubberduckParser.cs:line 46
   at Rubberduck.VBA.RubberduckParser.Parse(VBComponent component) in c:\Users\Mathieu\Source\Repos\Rubberduck\RetailCoder.VBE\VBA\RubberduckParser.cs:line 65

---

The `ExceptionErrorListener` has access to the `InputStream` through the `offendingToken` parameter, so technically yes, we could log an entire code module and reproduce the error. How about we disable it by default, and leave it up to the user to check a box that enables it?

**Comment by ckuhn203** [comment]
We could do that. I was thinking a `#If DEBUG` preprocessor, but yeah. I mean, if you think that's enough information to debug the grammar though, don't bother.

**Comment by retailcoder** [comment]
Okay I got it to work. NLog will create a `\logs` folder under `%appdata%\rubberduck`, alongside the .xml configuration. Currently there's only a `parser.log` file being generated, which is enough to close this issue :)
